lectures/_toc.yml
lectures/short_path.md

Shortest path JAX

---

lectures/_toc.yml
lectures/newtons_method.md

Hi @jstac, this PR fix issue #3.
I've moved over the jax part of Newton's Method lecture and added some brief introductions to this problem.

Newton's Method first edition

---

lectures/_toc.yml
lectures/opt_invest.md

Add a lecture on optimal investment

---

lectures/_toc.yml
lectures/aiyagari_jax.md

initialise_aj

---

lectures/_toc.yml
lectures/kesten_processes.md

Add Kesten Processes

---

lectures/_toc.yml
lectures/jax_intro.md

LECT: Migrate jax_intro lecture from python-programming

---

lectures/arellano.md
lectures/kesten_processes.md
lectures/wealth_dynamics.md

remove jit for fast compile solve #33

remove jit for fast compile

---

lectures/ifp_egm.md

Hi @jstac this PR fixes some typos in the lecture ``ifp_egm``.

minor_edits

---

lectures/_toc.yml
lectures/mle.md

Add MLE lecture

---

lectures/mle.md

Hi @jstac,
I added more details about the likelihood and log likelihood functions of Poisson regression. I think MLE can be a good example for a lecture on symbolic algebra since it has a routine that can be tedious to calculate by hand sometimes. It is also conceptually easy so that people can focus on the implementation. 
Please kindly review this PR and let me know if there is anything I can further improve.
Many thanks.

Update MLE Lecture with More Details

---

lectures/markov_asset.md

Hi @jstac, this PR fixes #73.
Could you please confirm again this is now correct?

Fix equation

---

lectures/opt_invest.md

Hi @jstac, this PR fixes the use of non-ascii symbols in Optimal Investment lecture.

Fix non-ascii symbols

---

lectures/inventory_dynamics.md

Fix a Small Bug in Inventory Dynamics Lecture

---

lectures/_toc.yml
lectures/cake_eating_numerical.md

Add cake_eating lecture

---

lectures/opt_savings.md

Hi @jstac,
This is a small update to collapse `pip` install in the optimal savings lecture. Please kindly review and merge if it looks good to you.
Many thanks in advance.

Collapse `pip` install in Optimal Savings

---

lectures/wealth_dynamics.md

- Have removed a block of code that runs the `lax.scan` implementation before it is defined.
- Fixed a typo that wrongly runs the `for` loop implementation after JIT compilation of the `lax.scan` version.
- Stated the initial parameters to be used (inferred from solution) for exercise 7.2.
All changes identical to the previous PR but made on a local branch instead

Update lecture 7 (try 2)

---

lectures/jax_intro.md

https://github.com/QuantEcon/lecture-jax/pull/87#issuecomment-1667002764

Intro: Add `jax.vmap` section

---

lectures/opt_savings.md

Remove Extra Model in Optimal Saving Lecture

---

lectures/markov_asset.md

Split the equation 4.18 into 2 lines

---

lectures/wealth_dynamics.md

Use `fori_loop` wherever possible

---

lectures/inventory_dynamics.md

Use `fori_loop`

---

lectures/kesten_processes.md

Use `fori_loop` in Kesten Processes

---

.github/workflows/cache.yml
.github/workflows/ci.yml
.github/workflows/publish.yml
environment.yml

This PR updates the following software
- python=3.11
- anaconda==2023.09
- quantecon-book-theme==0.6.0

MAINT: Update software stack

---

lectures/_static/lecture_specific/successive_approx.py
lectures/_static/lecture_specific/vfi.py
lectures/opt_invest.md
lectures/opt_savings.md

Create jax-jitted successive_approx in opt_invest and opt_savings.

Use JAX in successive_approx

---

_notebook_repo/README.md
_notebook_repo/environment.yml

This PR fixes a missing _notebook_repo template directory

MAINT: add in notebook_repo template directory

---

.github/workflows/cache.yml
.github/workflows/ci.yml
.github/workflows/publish.yml

This PR upgrades the backend docker container that uses `anaconda==2024.02`

MAINT: upgrade to anaconda==2024.02

---

lectures/_static/lecture_specific/successive_approx.py
lectures/_static/lecture_specific/vfi.py

Use callback in `successive_approx` and create JAX-jitted `successive_approx`

Use callback in `successive_approx`

---

lectures/_toc.yml

ENH: add back in ssd_inventory

---

lectures/_toc.yml
lectures/opt_savings_1.md
lectures/opt_savings_2.md

Split optimal savings lecture in two, add vmap version, numpy comparison.

Split optimal savings

---

lectures/opt_savings_1.md
lectures/opt_savings_2.md

Modified all vectorized routines in opt_savings_2 to use vmap.
Timing is similar and logic is clearer.

Use vmap throughout opt savings 2

---

lectures/_toc.yml
lectures/job_search.md

This PR adds a new JAX lecture on Job Search.
Fixes #167

Add job search lecture

---

lectures/_toc.yml
lectures/hopenhayn.md

This PR adds a new lecture on The Hopenhayn Entry-Exit Model.
Related to #168

Add Hopenhayn lecture

---

lectures/job_search.md

Remove risk sensitive parameter from basic model

Small fix to job search

---

lectures/_config.yml

This PR addresses https://github.com/QuantEcon/meta/issues/137

MAINT: update bibtex to author_year style

---

lectures/overborrowing.md

This PR collects status messages issued by `compute_equilibirum` and prints them at the end of iteration to return a cleaner output in the context of `jupyter-book`

[overborrowing] MAINT: collect status messages

---

lectures/wealth_dynamics.md

Update Wealth Distribution Dynamics Lecture

---

.github/workflows/ci.yml
.github/workflows/collab.yml

CI: Use github actions for colab testing

CI: Use github actions for colab testing

---

lectures/aiyagari_jax.md

Update aiyagari model to include CBC changes.  Misc improvements.

Update aiyagari model to include CBC changes

---

lectures/_toc.yml
lectures/autodiff.md
lectures/jax_intro.md

Adds automatic differentiation lecture

Added autodiff lecture

---

.github/workflows/cache.yml
.github/workflows/ci.yml
.github/workflows/publish.yml
environment.yml

MAINT: update to use anaconda=2024.06

---

lectures/overborrowing.md

Update overborrowing lecture

---

.github/workflows/cache.yml
.github/workflows/ci.yml
.github/workflows/publish.yml
environment.yml

MAINT: Upgrade software

---

lectures/keras.md

This PR fixes some minor typos and removes `Dense?` as a feature of jupyter lab through the pop up window.

[kears] fix minor typos

---

.github/workflows/cache.yml

This PR sets the cache to run weekly on Monday at 3am

MAINT: schedule cache to run weekly

---

.github/dependabot.yml

@jstac thanks for the email. 
This will enable `dependabot` which will automate these upgrades for this repository.

MAINT: enable dependabot
