QuantEcon/lecture-jax

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/linkcheck.yml, .github/workflows/publish.yml, environment.yml
This PR updates
Will do these post merge:
=> ENH: Prepare for LIVE Deployment

lectures/kesten_processes.md
Hi @mmcky, 
I have reduced the size of `M` in the `lax.scan` function. I am unable to login to the GPU server since the issue last time. Would you mind rebuilding the lecture to see if it is sufficiently small? This should take half of the memory compared to what we have previously.
Many thanks in advance.
(This is mentioned in https://github.com/QuantEcon/lecture-jax/issues/36)
=> Update Kesten Processes with Smaller Simulation Size

lectures/aiyagari_jax.md, lectures/arellano.md, lectures/inventory_dynamics.md, lectures/jax_intro.md, lectures/kesten_processes.md, lectures/newtons_method.md, lectures/opt_invest.md, lectures/opt_savings.md, lectures/short_path.md, lectures/status.md, lectures/wealth_dynamics.md
=> MAINT: Harmonise GPU admonition, remove backend checks + add nvidia-smi

lectures/_config.yml, lectures/inventory_dynamics.md, lectures/kesten_processes.md, lectures/troubleshooting.md, lectures/wealth_dynamics.md
=> MAINT: Standardise plot size and remove custom matplotlib requests

lectures/_admonition/gpu.md, lectures/aiyagari_jax.md, lectures/arellano.md, lectures/inventory_dynamics.md, lectures/jax_intro.md, lectures/kesten_processes.md, lectures/newtons_method.md, lectures/opt_invest.md, lectures/opt_savings.md, lectures/short_path.md, lectures/wealth_dynamics.md
This PR centralises the `gpu` admonition into `_admonitions/gpu.md`
=> MAINT: centralize admonitions for GPU

lectures/aiyagari_jax.md, lectures/arellano.md, lectures/ifp_egm.md, lectures/inventory_dynamics.md, lectures/kesten_processes.md, lectures/newtons_method.md, lectures/opt_invest.md, lectures/opt_savings.md, lectures/short_path.md, lectures/status.md, lectures/wealth_dynamics.md
=> ENH: include nvidia-smi across lectures

lectures/opt_invest.md, lectures/opt_savings.md
=> Fixes in opt savings

lectures/_config.yml, lectures/_toc.yml
=> MNT: Move lecture + remove for now

lectures/jax_intro.md, lectures/newtons_method.md
Shifted exercise on Newton's method to Newton lecture, fixed incorrect link
=> Shifted exercise, fixed errors

.github/workflows/ci.yml, environment.yml
This PR updates to `quantecon-book-theme==0.5.3` to enable colab as the default.
=> EH: Update theme for COLAB

lectures/markov_asset.md
This PR fixes `latex` builds
fixes #116
=> FIX: use split instead of equation environment multline

lectures/markov_asset.md
=> Update Shape of `g` in Asset Pricing Code

lectures/aiyagari_jax.md
Hi @jstac this PR fix #123 .
Looking forward to your review and comments.
=> [aiyagari_jax] replace dataclass with namedtuple

lectures/inventory_dynamics.md, lectures/kesten_processes.md, lectures/markov_asset.md, lectures/mle.md
This PR checks all lectures for the `gpu` admonition `include` directive and tidies up some `content` directives that are not required.
=> MAINT: check gpu admonitions and tidy up

.github/workflows/ci.yml, lectures/ifp_egm.md
Replaces https://github.com/QuantEcon/lecture-jax/pull/130 and fixes https://github.com/QuantEcon/lecture-jax/issues/128
=> [ifp_egm] Tidy up EGM, remove jitclass

README.md
This PR updates the readme to move towards a standardized style across the lectures. 
@jstac comments on this README I will capture for the `.github/lectures/README.md` template that I will then add to the QuantEcon manual to use when building a lecture repo. 
see https://github.com/QuantEcon/meta/issues/132
=> MAINT: update README for standard format

lectures/inventory_dynamics.md
Improved flow, used fori_loop instead of scan, removed kernel density estimator.
=> Updates to inventory dynamics lecture

lectures/opt_savings_1.md, lectures/opt_savings_2.md
=> Small patches to optimal savings

lectures/opt_savings_1.md
=> Minor edits to opt savings

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/publish.yml
This PR updates the `cml` runner action to `v2`. This is required as of today due to a deprecation in `v1` api.
=> MAINT: update github action versions

lectures/opt_invest.md, lectures/opt_savings_2.md
This PR has the following changes:
- Adds visual comparison of HPI, VFI and OPI outputs using plots in `opt_invest.md` and `opt_savings_2.md`
Fixes #165
=> Add visual comparison of HPI, VFI and OPI outputs

lectures/_config.yml
This PR fixes the following warning that comes from CI:
```
WARNING: tojupyter_static_path entry /__w/lecture-jax/lecture-jax/lectures/source/_static does not exist
```
See https://github.com/QuantEcon/lecture-jax/actions/runs/8555440893/job/23442936380?pr=173#step:9:112 for reference.
Also, adds `JAX` as keywords in config.
=> Fix incorrect path warning in CI

.github/workflows/collab.yml
This PR addresses https://github.com/QuantEcon/meta/issues/139
=> ENH: Test Execution for Google Collab

lectures/lucas_model.md, lectures/troubleshooting.md
This PR removes `contents` directives to simplify
=> MAINT: remove %matplotlib inline and contents directive

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, environment.yml, lectures/status.md
This PR makes use of the `Tesla T4` instance now available on `GitHub Actions` as a beta instance. 
this migrates
to run on GitHub actions.
=> MAINT: use Github based GPU instance

lectures/autodiff.md, lectures/job_search.md, lectures/newtons_method.md
=> Update job search lecture

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, environment.yml
=> MAINT: Upgrade to anaconda=2024.10

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/collab.yml, .github/workflows/publish.yml
This PR migrates to use `quantecon-gpu-runner` to centralise on our runner group for gpu workloads.
=> MAINT: use quantecon-gpu-runner

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/collab.yml, .github/workflows/publish.yml
This is a minor maintenance PR to update the name of the `quantecon-gpu` runner on GitHub
=> MAINT: rename gpu runner for QuantEcon

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, environment.yml
=> MAINT: upgrade to jupyter-book==1.0.3

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/collab.yml, .github/workflows/publish.yml, scripts/test-jax-install.py
This PR migrates GitHub Actions to use [RunsOn](https://runs-on.com) which enables more customisable hardware choices and will be less expensive to build.
Migrates:
This is running on
- ubuntu 24.04
- CUDA=12.8 (currently)
- 8 vCPU
- 1 x Tesla T4 (GPU)
=> ENH: use runs-on for Github Actions

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/publish.yml
This PR migrates github actions to use the custom quantecon ami
=> MAINT: update GA to run custom quantecon ami

lectures/overborrowing.md
This PR reviews and fixes FutureWarnings
the seaborn package appears to have resolved its warning issue so I have removed the suppression.
=> MAINT: review and fix FutureWarnings

.github/workflows/ci.yml, lectures/kesten_processes.md
=> Kesten edits

lectures/kesten_processes.md
Fixed some typos and an incorrect comparison :grimacing: 
@mmcky , would you mind to review?
=> Kesten fixes part 2

lectures/jax_intro.md
This PR fixes description on `at` method, emphasizing it is pure.
=> [FIX] Fix descriptions on `.at` method

lectures/inventory_dynamics.md
Switches from namedtuple to class(NamedTuple) for nicer, cleaner syntax.
Adds typing.
Simplifies the fori_loop discussion by removing the option of generating all shocks at once (which doesn't help much and requires more memory).
The coding style changes can be used as a model for updates to other lectures.
=> Updates to inventory lecture

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/publish.yml, environment.yml, lectures/jax_intro.md, lectures/status.md
This PR updates
- `anaconda=2025.06`
- `python=3.13`
=> MAINT: upgrade anaconda=2025.06 and python=3.13
